DROP TABLE IF EXISTS steam_discount_game, steam_featured_game;

CREATE TABLE steam_discount_game(
  ID SERIAL,
  NAME TEXT NOT NULL,
  LINK TEXT NOT NULL,
  IMG_SRC TEXT,
  REVIEW TEXT,
  PRICE_BEFORE FLOAT,
  PRICE_NOW FLOAT,
  DISCOUNT FLOAT
);

CREATE TABLE steam_featured_game(
  ID SERIAL,
  NAME TEXT NOT NULL,
  LINK TEXT NOT NULL,
  IMG_SRC TEXT,
  HEADLINE TEXT,
  PRICE_BEFORE FLOAT,
  PRICE_NOW FLOAT,
  DISCOUNT FLOAT,
  FEATURE_TYPE VARCHAR(20)
);

-- Insert one example record.
INSERT INTO steam_discount_game (NAME, LINK) VALUES (
  'EXAMPLE_GAME',
  'localhost'
);
